name: iosApp
options:
  bundleIdPrefix: com.arg
  deploymentTarget:
    iOS: '15.0'
  createIntermediateGroups: true

targets:
  NutriIA:
    type: application
    platform: iOS
    deploymentTarget: '15.0'
    sources:
      - path: iosApp/iosApp
        excludes:
          - '*.png'
          - Info.plist
    info:
      path: iosApp/iosApp/Info.plist
      properties:
        CFBundleShortVersionString: '2.2.5'
        CFBundleVersion: '27'
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arg.nutriia
        DEVELOPMENT_TEAM: X423NH338U
        CODE_SIGN_STYLE: Manual
        IPHONEOS_DEPLOYMENT_TARGET: '15.0'
        SWIFT_VERSION: '5.0'
        TARGETED_DEVICE_FAMILY: '1'
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: iosApp/iosApp/Info.plist
        CURRENT_PROJECT_VERSION: '27'
        MARKETING_VERSION: '2.2.5'
        FRAMEWORK_SEARCH_PATHS: '$(SRCROOT)/shared/build/bin/iosArm64/releaseFramework'
        LD_RUNPATH_SEARCH_PATHS: '@executable_path/Frameworks'
    dependencies:
      - framework: shared/build/bin/iosArm64/releaseFramework/Shared.framework
        embed: false
